version: '3.8'

services:
  notebook:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: notebook_local
    container_name: notebook_local
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    ports:
      - 8080:8888
    env_file:
      - .env
